# Generated by Django 4.0.5 on 2022-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='author',
            field=models.CharField(max_length=60),
        ),
    ]
