# Generated by Django 4.0 on 2022-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='topic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
