# Generated by Django 4.0 on 2022-06-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0004_rename_question_comments_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='BlogComment',
        ),
    ]
